### ISSUE TITLE
Problem in model.evaluate size of x1,x2 and y (181240, 32) (181240, 32) (181240,) respectively

### ISSUE THREAD

**Issue by AnkitSnh2** [email81227/Time2Vec-TensorFlow2#1]
File "run.py", line 73, in <module>
    model.evaluate([ts_X1, ts_X2], ts_y)
  File "C:\Users\ankit\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\engine\training.py", line 1102, in evaluate
    batch_size=batch_size)
  File "C:\Users\ankit\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\engine\training.py", line 751, in _standardize_user_data
    exception_prefix='input')
  File "C:\Users\ankit\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\engine\training_utils.py", line 128, in standardize_input_data
    'with shape ' + str(data_shape))
ValueError: Error when checking input: expected input_2 to have 3 dimensions, but got array with shape (181240, 32)

**Comment by email81227** [comment]
Hi AnkitSnh2,
I can not reproduce this error. 
If any modification of the run.py, can you share it with me?
Or the version of tensorflow / Keras used.

**Comment by AnkitSnh2** [comment]
The modification I did was just to use keras layer instead of using mix of keras and tensorflow. I am just using keras to add layers now (removed all dependency from tensorflow). The version of the libraries are Python3.6, Keras 2.2.4, TF 1.1.15.

**Comment by email81227** [comment]
Maybe you can try using `model.evaluate([ts_X1.reshape((-1, SEQ_LEN, 1)), ts_X2.reshape((-1, SEQ_LEN, 1))], ts_y)` instead of `model.evaluate([ts_X1, ts_X2], ts_y)`.

If the above works, I guess this is because the attribute `compute_output_shape` of the Time2Vec layer working great in Keras 2.24 and TF 1 backend but not working as expected in TF2.

Similar issue here: [Is it still necessary to implement `compute_output_shape()` when defining a custom tf.keras Layer?](https://stackoverflow.com/questions/61522019/is-it-still-necessary-to-implement-compute-output-shape-when-defining-a-cust)

**Comment by AnkitSnh2** [comment]
Thanks for the suggestion. Indeed this was the problem. I will close the issue now. Thanks again.
